# Generated by Django 4.2.3 on 2023-08-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('puntaje', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_1', models.CharField(max_length=100)),
                ('actor_2', models.CharField(max_length=100)),
                ('reseña', models.TextField()),
            ],
        ),
    ]
